	SELECT 
		DATETIME(ZVIBERMESSAGE.ZDATE+978307200,'UNIXEPOCH') AS 'Date',
		ZPHONENUMBERINDEX.ZNAME AS 'Name',
		ZPHONENUMBERINDEX.ZPHONENUM AS 'Number',
		ZVIBERMESSAGE.ZSTATE AS 'State',
		--Z_4PHONENUMINDEXES.Z_4CONVERSATIONS,
		--Z_4PHONENUMINDEXES.Z_8PHONENUMINDEXES,
		ifnull(ZVIBERMESSAGE.ZCALLTYPE,'message') AS 'Type',
		ZVIBERMESSAGE.ZTEXT AS 'Text',
		ZATTACHMENT.ZFILESIZE AS 'Attachment size',
		ZATTACHMENT.ZNAME AS 'Attachment'
	FROM ZVIBERMESSAGE
	LEFT JOIN ZCONVERSATION ON ZCONVERSATION.Z_PK = ZVIBERMESSAGE.ZCONVERSATION
	LEFT JOIN Z_4PHONENUMINDEXES ON Z_4PHONENUMINDEXES.Z_4CONVERSATIONS = ZCONVERSATION.Z_PK
	LEFT JOIN ZPHONENUMBERINDEX ON ZPHONENUMBERINDEX.Z_PK = Z_4PHONENUMINDEXES.Z_8PHONENUMINDEXES
	LEFT JOIN ZATTACHMENT ON ZATTACHMENT.ZMESSAGE = ZVIBERMESSAGE.Z_PK
	ORDER BY DATUM
